---
jwt:
  sign-in-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=helpdesk
    username: help-desk
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
