---
logging:
  level:
    com.cotech.helpdesk: TRACE
    com.zaxxer.hikari.pool: INFO
    org:
      apache:
        tomcat.level: INFO
        tomcat.util.net: WARN
      springframework:
        security: INFO
        helpdesk: TRACE
jwt:
  sign-in-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=helpdesk
    username: help-desk
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /swagger/api-docs
  swagger-ui:
    enabled: true
    path: /swagger/swagger-ui