---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=expense_tracking
    username: expense-tracking
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true

