name: Build using gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Setup JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: temurin
#          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
            build-scan-publish: true
            build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
            build-scan-terms-of-use-agree: "yes"

      - name: List Directory files
        run: ls ${{ github.workspace }}
      - name: Gradle Version
        run: gradle --version
      - name: Build with Gradle
        run: ./gradlew build
